"""add project visibility

Revision ID: 3604d51b52a9
Revises: 3e9676e1e52d
Create Date: 2026-08-14 21:16:07.844857

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = '3604d51b52a9'
down_revision: str | Sequence[str] | None = '3e9676e1e52d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('visibility', sa.String(length=20), server_default=sa.text("'private'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'visibility')
    # ### end Alembic commands ###
