"""add project owner

Revision ID: 3e9676e1e52d
Revises: eaf25322a0fc
Create Date: 2026-08-14 20:28:07.150360

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = '3e9676e1e52d'
down_revision: str | Sequence[str] | None = 'eaf25322a0fc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('owner_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_projects_owner_id'), 'projects', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_owner_id'), table_name='projects')
    op.drop_column('projects', 'owner_id')
    # ### end Alembic commands ###
