"""add public access role

Revision ID: b43779e6561a
Revises: c9a67bf4e8e6
Create Date: 2026-08-14 21:31:37.446520

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = 'b43779e6561a'
down_revision: str | Sequence[str] | None = 'c9a67bf4e8e6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('public_access_role', sa.String(length=20), server_default=sa.text("'viewer'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'public_access_role')
    # ### end Alembic commands ###
